### ISSUE TITLE
Changing Text in Showcase-3 on index.html duplicates text on save

### ISSUE THREAD

**Issue by Twilight-Computer** [givanz/Vvveb#187]
Editing the text in the Showcase-3 section on index.html.

Using the Code Editor or the GUI - on save, it duplicates the text.

Editing the file manually (index.html in public/themes/landing ) does not show this duplicated text.

**Comment by givanz** [comment]
Thanks for the bug report, it was caused by a chrome bug that adds div elements inside paragraphs on enter key.

It's fixed in the latest update, changed file [public/js/vvvebjs/builder.js](https://github.com/givanz/Vvveb/blob/master/public/js/vvvebjs/builder.js)

You might need to clear browser cache after update.

**Comment by Twilight-Computer** [comment]
I have updated my test site to the latest V1.04. Problem is still present.
Checked and confirmed that my builder.js file is same as one shown on source and they match.
Clearing browser cache adds more lines of text.......

**Comment by givanz** [comment]
Can you please try on a newly added Showcase-3 section? 

The existing section might have a wrong structure from the previous bug with div elements inside p that might prevent text editing to work properly.

Or you can make a quick check on the demo https://demo.vvveb.com/admin/index.php?module=editor/editor&url=/&template=index.html
