### ISSUE TITLE
Installation Error, 502 Bad Gateway, from page /install/index.php

### ISSUE THREAD

**Issue by Vander-Bilt** [givanz/Vvveb#217]
I followed the installation document [https://docs.vvveb.com/installation](https://docs.vvveb.com/installation) / setting up nginx & php,    trying to access localhost:8080, then got below error:
![image](https://github.com/user-attachments/assets/3289b29e-4633-4f9a-ab16-9e85daa67fbe)

It can be seen that the error occurred on the **/install/index.php** page.

My development environment is as follows.

**php**

![image](https://github.com/user-attachments/assets/2aa9b122-ca8d-4043-ac86-a100d1d9a9ca)

![image](https://github.com/user-attachments/assets/98f874e2-c71d-4a46-9bab-91874fba3a29)

**nginx**

```
#user  nobody;
worker_processes  1;


error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {

    fastcgi_cache_path /var/run/nginx-vvveb_cache levels=1:2 keys_zone=VCACHE:100m inactive=30m;
    fastcgi_cache_key "$scheme$request_method$host$request_uri";
    fastcgi_cache_use_stale error timeout invalid_header http_500;

    #sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    #keepalive_timeout  65;

    #gzip  on;

    server {
        listen       0.0.0.0:8080;
        server_name  localhost;

        #root html;
        root /usr/local/var/vvveb/public;
        index index.php index.html index.htm;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

    
        gzip on;
        gzip_vary on;
        gzip_min_length 10240;
        gzip_proxied any;
        gzip_comp_level 6;
        gzip_buffers 16 8k;
        gzip_http_version 1.1;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

        #charset utf-8;

        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";

        set $skip_cache 0;
        set $cache_uri $request_uri;


        if ($query_string != "") {
            set $skip_cache 1;
            set $cache_uri null;
        }

        # Don't cache uris containing the following segments
        if ($request_uri ~* "/admin/|/user/|/cart/|/feed/|index.php|sitemap(_index)?.xml") {
            set $skip_cache 1;
            set $cache_uri null;
        }  

        # Don't use the cache for logged in users or if products in cart
        if ($http_cookie ~* "nocache|user|cart") {
            set $skip_cache 1;
            set $cache_uri null;
        }

        # POST requests and urls with a query string should always go to PHP
        if ($request_method = POST) {
            set $skip_cache 1;
            set $cache_uri null;
        }

        #add domain to sitemaps for multisite
        location = /robots.txt {
            log_not_found off;
            access_log off;
            try_files $uri /index.php$is_args$args;
        }
        
        #static files	
        location ~* "\.(?!php)([\w]{3,5})$" {
            expires max;
            log_not_found off;
            sendfile           on;
            sendfile_max_chunk 1m;
            fastcgi_hide_header "Set-Cookie";
        }

        location / {
            #try_files $uri $uri/ =404;
            default_type  text/html;
            index index.php index.html index.htm;
            try_files /page-cache/$http_host$cache_uri /page-cache/$http_host$cache_uri/index.html $uri $uri/ /index.php$is_args$args;
            #try_files $uri $uri/ /index.php$is_args$args;

            #cache debug
            #add_header "uri" $cache_uri;
            #add_header "skip_cache" $skip_cache;
        }

        location ~ /media/.+?\.php$ {
            deny all;
        }

        location ~ \.php$ {
            include fastcgi.conf;
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

            fastcgi_intercept_errors        on;

            #uncomment fastcgi_cache to enable fastcgi cache, this should not be necessary
            #unless you set the path to a memory mapped location for even faster cache
            
            #fastcgi_cache VCACHE;          
            fastcgi_cache_bypass $skip_cache;
            fastcgi_no_cache $skip_cache;
            fastcgi_cache_valid 30m;
            #add_header X-VCache $upstream_cache_status;  
        }

        location ~ /\.(?!well-known).* {
            deny all;
        }
}

```

**I found some error info in Nginx log**, but I didn't know what led to it.

![image](https://github.com/user-attachments/assets/75e95caf-6b6a-4496-bbf3-bf27531bc26f)

**I tried to put a simple php file as test, it works well.**
```
<?php 
phpinfo(); 
?>

```
![image](https://github.com/user-attachments/assets/46fc0482-f997-44e3-a033-9fee7fa6d305)

**Comment by givanz** [comment]
Can you also please check your php error log? this is probably caused by a php fatal error.

**Comment by KishUltan** [comment]
2026/04/27 10:18:56 [error] 5134#0: *21341 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /install/index.php HTTP/1.1", upstream: "fastcgi://unix:/usr/local/var/run/php-fpm-8.4.sock:", host: "localhost:84"
2026/04/27 10:18:56 [error] 5134#0: *21341 FastCGI sent in stderr: "PHP message: PHP Deprecated:  exit(): Passing null to parameter #1 ($status) of type string|int is deprecated in /Users/abc/workspace/Vvveb/index.php on line 75" while reading response header from upstream, client: 127.0.0.1, server: _, request: "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1", upstream: "fastcgi://unix:/usr/local/var/run/php-fpm-8.4.sock:", host: "localhost:84"

**Comment by givanz** [comment]
Thanks for the bug report.

It's fixed in latest.zip please redownload the zip and overwrite the files.

**Comment by KishUltan** [comment]
> Thanks for the bug report.
> 
> It's fixed in latest.zip please redownload the zip and overwrite the files.

Thanks for the update.

I re-tested with the latest zip. It fixes the Deprecated: exit() notice, but the original installer 502 is still reproducible in my environment.

From logs and core dump, this is a PHP-FPM worker crash (SIGSEGV) in the native gettext path (zif_gettext -> libintl), not a normal PHP warning/exception. So it appears to be a separate root cause from the deprecation fix.

I submitted a PR with the fix/workaround and related installer compatibility fixes:
https://github.com/givanz/Vvveb/pull/424

Included in the PR:

Avoid native gettext path on affected environment (macOS + fpm-fcgi) to prevent SIGSEGV.
Fix MySQL ANSI_QUOTES installer schema compatibility (DEFAULT "" -> DEFAULT '').
Fix INFORMATION_SCHEMA metadata query quoting in mysqli driver.

**Comment by givanz** [comment]
Thanks for the PR.

I checked the SIGSEGV bug and it's fixed in PHP 8.4.4 https://github.com/php/php-src/commit/e975c27e12ef11a625bc7015ddd1de87b3c5cd18

https://www.php.net/ChangeLog-8.php#8.4.4

Same issue on mac https://github.com/beyondcode/herd-community/issues/1656

Can you please upgrade PHP and see if it works?


Do you have issues with install when using sql_mode = 'ANSI' in mysql?

Can you please provide mysql/mariadb version to make tests? 

I think that there might be more post install code including queries that can be affected by ansi flag.

Is there a reason to force ansi for mysql?

**Comment by KishUltan** [comment]
Thanks for the clarification.

Quick correction after re-testing:

PHP upgrade / SIGSEGV
The installer 502 issue is still reproducible on both PHP 8.5.5 and PHP 8.4.13 in my environment.

Nginx still logs:

upstream prematurely closed connection while reading response header from upstream
PHP-FPM still reports:

child exited on signal 11 (SIGSEGV)
Core dump backtrace still points to native gettext path (zif_gettext -> libintl), so in my setup the upgrade did not eliminate this crash.

```

Core file '/cores/core.pid' (x86_64) was loaded.
* thread #1
  * frame #0: 0x00007ff819787679 libdispatch.dylib`_dispatch_apply_with_attr_f + 1182
    frame #1: 0x00007ff819787847 libdispatch.dylib`dispatch_apply + 45
    frame #2: 0x00007ff819b0dbe5 CoreFoundation`__103-[CFPrefsSearchListSource synchronouslySendSystemMessage:andUserMessage:andDirectMessage:replyHandler:]_block_invoke.75 + 97
    frame #3: 0x00007ff8199ab6a6 CoreFoundation`CFPREFERENCES_IS_WAITING_FOR_SYSTEM_AND_USER_CFPREFSDS + 74
    frame #4: 0x00007ff819b0cfda CoreFoundation`-[CFPrefsSearchListSource synchronouslySendSystemMessage:andUserMessage:andDirectMessage:replyHandler:] + 181
    frame #5: 0x00007ff8199a9fe9 CoreFoundation`-[CFPrefsSearchListSource alreadylocked_generationCountFromListOfSources:count:] + 220
    frame #6: 0x00007ff8199a9d1c CoreFoundation`-[CFPrefsSearchListSource alreadylocked_getDictionary:] + 391
    frame #7: 0x00007ff8199a98e0 CoreFoundation`-[CFPrefsSearchListSource alreadylocked_copyValueForKey:] + 150
    frame #8: 0x00007ff8199a982c CoreFoundation`-[CFPrefsSource copyValueForKey:] + 47
    frame #9: 0x00007ff8199a97dd CoreFoundation`__76-[_CFXPreferences copyAppValueForKey:identifier:container:configurationURL:]_block_invoke + 32
    frame #10: 0x00007ff8199a22b3 CoreFoundation`__108-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]_block_invoke + 361
    frame #11: 0x00007ff819b0e398 CoreFoundation`-[_CFXPreferences withSearchListForIdentifier:container:cloudConfigurationURL:perform:] + 403
    frame #12: 0x00007ff8199a1bf3 CoreFoundation`-[_CFXPreferences copyAppValueForKey:identifier:container:configurationURL:] + 137
    frame #13: 0x00007ff8199a1b28 CoreFoundation`_CFPreferencesCopyAppValueWithContainerAndConfiguration + 101
    frame #14: 0x0000000108df6b7e libintl.8.dylib`_libintl_locale_name_default + 66
    frame #15: 0x0000000108df3a3d libintl.8.dylib`libintl_dcigettext + 613
    frame #16: 0x00000001076462ee php-fpm`zif_gettext + 72
    frame #17: 0x0000000107ac2b75 php-fpm`ZEND_DO_FCALL_BY_NAME_SPEC_RETVAL_USED_HANDLER + 334
    frame #18: 0x0000000107a8b32d php-fpm`execute_ex + 99
    frame #19: 0x0000000107a8b53f php-fpm`zend_execute + 336
    frame #20: 0x0000000107b352c9 php-fpm`zend_execute_script + 80
    frame #21: 0x00000001079e71be php-fpm`php_execute_script_ex + 458
    frame #22: 0x0000000107b40b9f php-fpm`main + 6743
    frame #23: 0x00007ff8195bb418 dyld`start + 1896
* thread #1
  * frame #0: 0x00007ff819787679 libdispatch.dylib`_dispatch_apply_with_attr_f + 1182
    frame #1: 0x00007ff819787847 libdispatch.dylib`dispatch_apply + 45
    frame #2: 0x00007ff819b0dbe5 CoreFoundation`__103-[CFPrefsSearchListSource synchronouslySendSystemMessage:andUserMessage:andDirectMessage:replyHandler:]_block_invoke.75 + 97
    frame #3: 0x00007ff8199ab6a6 CoreFoundation`CFPREFERENCES_IS_WAITING_FOR_SYSTEM_AND_USER_CFPREFSDS + 74
    frame #4: 0x00007ff819b0cfda CoreFoundation`-[CFPrefsSearchListSource synchronouslySendSystemMessage:andUserMessage:andDirectMessage:replyHandler:] + 181
    frame #5: 0x00007ff8199a9fe9 CoreFoundation`-[CFPrefsSearchListSource alreadylocked_generationCountFromListOfSources:count:] + 220
    frame #6: 0x00007ff8199a9d1c CoreFoundation`-[CFPrefsSearchListSource alreadylocked_getDictionary:] + 391
    frame #7: 0x00007ff8199a98e0 CoreFoundation`-[CFPrefsSearchListSource alreadylocked_copyValueForKey:] + 150
    frame #8: 0x00007ff8199a982c CoreFoundation`-[CFPrefsSource copyValueForKey:] + 47
    frame #9: 0x00007ff8199a97dd CoreFoundation`__76-[_CFXPreferences copyAppValueForKey:identifier:container:configurationURL:]_block_invoke + 32
    frame #10: 0x00007ff8199a22b3 CoreFoundation`__108-[_CFXPreferences(SearchListAdditions) withSearchListForIdentifier:container:cloudConfigurationURL:perform:]_block_invoke + 361
    frame #11: 0x00007ff819b0e398 CoreFoundation`-[_CFXPreferences withSearchListForIdentifier:container:cloudConfigurationURL:perform:] + 403
    frame #12: 0x00007ff8199a1bf3 CoreFoundation`-[_CFXPreferences copyAppValueForKey:identifier:container:configurationURL:] + 137
    frame #13: 0x00007ff8199a1b28 CoreFoundation`_CFPreferencesCopyAppValueWithContainerAndConfiguration + 101
    frame #14: 0x0000000108df6b7e libintl.8.dylib`_libintl_locale_name_default + 66
    frame #15: 0x0000000108df3a3d libintl.8.dylib`libintl_dcigettext + 613
    frame #16: 0x00000001076462ee php-fpm`zif_gettext + 72
    frame #17: 0x0000000107ac2b75 php-fpm`ZEND_DO_FCALL_BY_NAME_SPEC_RETVAL_USED_HANDLER + 334
    frame #18: 0x0000000107a8b32d php-fpm`execute_ex + 99
    frame #19: 0x0000000107a8b53f php-fpm`zend_execute + 336
    frame #20: 0x0000000107b352c9 php-fpm`zend_execute_script + 80
    frame #21: 0x00000001079e71be php-fpm`php_execute_script_ex + 458
    frame #22: 0x0000000107b40b9f php-fpm`main + 6743
    frame #23: 0x00007ff8195bb418 dyld`start + 1896

```

MySQL ANSI_QUOTES details
My DB environment is:

MySQL: 8.0.42
sql_mode: ANSI_QUOTES,STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
With this mode, installer SQL fails where double quotes are used as string literals (e.g. DEFAULT "", TABLE_SCHEMA="db"), because " is treated as identifier quoting under ANSI_QUOTES.

So the MySQL quoting fixes in PR #424 remain relevant independently of the PHP crash.
